Fix makesdna error due to poor comment parsing, should be fixed in makesdna ideally but for now just tweak code in case it causes issues.
ERROR: still 1 structs unknown
*** Unknown structs: bSound